title: "蟹壳"

plugins:
    - jekyll-mentions
    - jemoji
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-polyglot
defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"
excerpt_separator: <!--more-->

paginate: 15
paginate_path: "/essays/p-:num"

# https://leo3418.github.io/zh/collections/multilingual-jekyll-site/localize-strings.html
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true